function createRdEvolutionGif( ...
        rdEnhancedDb, targetData, derived, cfg, outputPath)
%CREATERDEVOLUTIONGIF Export background-enhanced RD as GIF.

    pradar.createRdCubeGif( ...
        rdEnhancedDb, ...
        targetData, ...
        derived, ...
        cfg, ...
        outputPath, ...
        "Background-enhanced RD evolution", ...
        cfg.rdGifClim);
end