function candidateTable = extractVelocityCandidates( ...
        velocityTimeMapDb, rangeMap, targetData, derived, cfg)
%EXTRACTVELOCITYCANDIDATES
% Extract multiple velocity candidates from every short-time window.

    globalWindow = [];
    physicalFrame = [];
    windowInFrame = [];
    timeMs = [];
    rangeM = [];
    aliasedVelocity = [];
    relativeStrength = [];
    rangeBin = [];
    velocityBin = [];

    velocityAxis = derived.velocityAxis(:);
    rangeAxis = derived.rangeAxis(:);
    velocityGate = derived.velocityMask(:);

    for windowIndex = 1:size(velocityTimeMapDb, 2)

        profile = double( ...
            velocityTimeMapDb(:, windowIndex));

        profileSmooth = movmean( ...
            profile, ...
            cfg.velocitySmoothBins, ...
            'omitnan');

        % Reject velocity bins excluded by the current velocity mask.
        profileSmooth(~velocityGate) = -Inf;

        % Doppler axis is circular, so use circular neighbours
        % for local-peak detection.
        leftProfile = circshift(profileSmooth, 1);
        rightProfile = circshift(profileSmooth, -1);

        isLocalPeak = ...
            profileSmooth >= leftProfile ...
            & profileSmooth > rightProfile ...
            & velocityGate;

        peakIndices = find( ...
            isLocalPeak ...
            & profileSmooth >= cfg.candidateThresholdDb);

        if isempty(peakIndices)
            continue;
        end

        [~, order] = ...
            sort(profileSmooth(peakIndices), 'descend');

        peakIndices = peakIndices(order);

        selectedIndices = [];

        for peakIndex = 1:numel(peakIndices)

            currentBin = peakIndices(peakIndex);
            currentVelocity = velocityAxis(currentBin);

            if isempty(selectedIndices)

                separated = true;

            else

                velocityDifference = abs( ...
                    velocityAxis(selectedIndices) ...
                    - currentVelocity);

                % Circular Doppler distance:
                % +Vmax and -Vmax are adjacent physically.
                velocityDifference = min( ...
                    velocityDifference, ...
                    derived.velocityPeriod ...
                    - velocityDifference);

                separated = all( ...
                    velocityDifference ...
                    >= cfg.minVelocityCandidateSeparation);
            end

            if separated

                selectedIndices(end + 1) = ...
                    currentBin; %#ok<AGROW>

                if numel(selectedIndices) ...
                        >= cfg.maxCandidatesPerWindow
                    break;
                end
            end
        end

        for selectedIndex = 1:numel(selectedIndices)

            currentVelocityBin = ...
                selectedIndices(selectedIndex);

            currentVelocity = ...
                velocityAxis(currentVelocityBin);

            currentRange = double( ...
                rangeMap( ...
                    currentVelocityBin, ...
                    windowIndex));

            if ~isfinite(currentRange)
                continue;
            end

            [~, currentRangeBin] = min( ...
                abs(rangeAxis - currentRange));

            globalWindow(end + 1, 1) = ...
                windowIndex; %#ok<AGROW>

            physicalFrame(end + 1, 1) = ...
                targetData.windowPhysicalFrame( ...
                    windowIndex); %#ok<AGROW>

            windowInFrame(end + 1, 1) = ...
                targetData.windowIndexInFrame( ...
                    windowIndex); %#ok<AGROW>

            timeMs(end + 1, 1) = ...
                targetData.windowTimeMs( ...
                    windowIndex); %#ok<AGROW>

            rangeM(end + 1, 1) = ...
                currentRange; %#ok<AGROW>

            aliasedVelocity(end + 1, 1) = ...
                currentVelocity; %#ok<AGROW>

            relativeStrength(end + 1, 1) = ...
                profileSmooth( ...
                    currentVelocityBin); %#ok<AGROW>

            rangeBin(end + 1, 1) = ...
                currentRangeBin; %#ok<AGROW>

            velocityBin(end + 1, 1) = ...
                currentVelocityBin; %#ok<AGROW>
        end
    end

    candidateTable = table( ...
        globalWindow, ...
        physicalFrame, ...
        windowInFrame, ...
        timeMs, ...
        rangeM, ...
        aliasedVelocity, ...
        relativeStrength, ...
        rangeBin, ...
        velocityBin, ...
        'VariableNames', { ...
            'GlobalWindow', ...
            'PhysicalFrame', ...
            'WindowInFrame', ...
            'Time_ms', ...
            'Range_m', ...
            'AliasedVelocity_mps', ...
            'RelativeStrength_dB', ...
            'RangeBin', ...
            'VelocityBin'});
end