function figures = plotResults(result)
%PLOTRESULTS Create the four standard analysis figures.

    cfg = result.cfg;
    derived = result.derived;
    targetData = result.targetData;
    candidateTable = result.candidateTable;
    trackTable = result.trackTable;
    fitInfo = result.fitInfo;
    metrics = result.velocityMetrics;

    visibleValue = 'off';
    if cfg.plotVisible
        visibleValue = 'on';
    end

    rawDb = 10 * log10(targetData.rangePowerTime + single(1e-12));
    rawMaximum = max(rawDb(isfinite(rawDb)));

    ax1 = pradar.drawSegmentedMap( ...
        targetData.chirpTimeMs, derived.rangeAxis, rawDb, ...
        cfg.numChirpsPerFrame, targetData.numFrames, ...
        'Figure 1: Raw range-time', ...
        sprintf('Raw range-time: physical frames %d-%d', ...
            cfg.targetFrameStart, cfg.targetFrameEnd), ...
        [cfg.displayRangeMin, cfg.displayRangeMax], ...
        [rawMaximum - cfg.rawDynamicRangeDb, rawMaximum], visibleValue);
    pradar.addFrameLines(ax1, targetData.numFrames, ...
        cfg.framePeriod, cfg.numChirpsPerFrame * cfg.chirpPeriod);

    ax2 = pradar.drawSegmentedMap( ...
        targetData.chirpTimeMs, derived.rangeAxis, ...
        result.rangeTimeEnhancedDb, cfg.numChirpsPerFrame, ...
        targetData.numFrames, 'Figure 2: Enhanced range-time', ...
        sprintf('Background-enhanced range-time: physical frames %d-%d', ...
            cfg.targetFrameStart, cfg.targetFrameEnd), ...
        [cfg.displayRangeMin, cfg.displayRangeMax], ...
        cfg.chirpEnhancedClim, visibleValue);
    pradar.addFrameLines(ax2, targetData.numFrames, ...
        cfg.framePeriod, cfg.numChirpsPerFrame * cfg.chirpPeriod);

    %% Figure 3: selected RD projection

    switch cfg.rdProjectionMode

        case "range"

            ax3 = pradar.drawSegmentedMap( ...
                targetData.windowTimeMs, ...
                derived.rangeAxis, ...
                result.rdEnhancedRangeTimeDb, ...
                derived.windowsPerFrame, ...
                targetData.numFrames, ...
                'Figure 3: RD-compressed range-time', ...
                sprintf( ...
                    'Velocity-compressed RD and track: %s', ...
                    cfg.caseId), ...
                [cfg.displayRangeMin, cfg.displayRangeMax], ...
                cfg.rdEnhancedRangeTimeClim, ...
                visibleValue);

            pradar.addFrameLines( ...
                ax3, ...
                targetData.numFrames, ...
                cfg.framePeriod, ...
                cfg.numChirpsPerFrame ...
                    * cfg.chirpPeriod);

            hold(ax3, 'on');

            if ~isempty(candidateTable)

                plot( ...
                    ax3, ...
                    candidateTable.Time_ms, ...
                    candidateTable.Range_m, ...
                    'wo', ...
                    'LineStyle', 'none', ...
                    'MarkerSize', 5, ...
                    'LineWidth', 0.8);
            end

            if fitInfo.valid

                plot( ...
                    ax3, ...
                    trackTable.Time_ms, ...
                    trackTable.Range_m, ...
                    'r-o', ...
                    'MarkerFaceColor', 'y', ...
                    'MarkerSize', 6, ...
                    'LineWidth', 1.6);

                fitTimeMs = linspace( ...
                    min(trackTable.Time_ms), ...
                    max(trackTable.Time_ms), ...
                    300);

                fitRange = ...
                    fitInfo.speed ...
                    * fitTimeMs * 1e-3 ...
                    + fitInfo.intercept;

                plot( ...
                    ax3, ...
                    fitTimeMs, ...
                    fitRange, ...
                    'w--', ...
                    'LineWidth', 1.3);
            end

            hold(ax3, 'off');


        case "velocity"

            ax3 = pradar.drawSegmentedMap( ...
                targetData.windowTimeMs, ...
                derived.velocityAxis, ...
                result.rdEnhancedVelocityTimeDb, ...
                derived.windowsPerFrame, ...
                targetData.numFrames, ...
                'Figure 3: RD-compressed velocity-time', ...
                sprintf( ...
                    'Range-compressed RD and track: %s', ...
                    cfg.caseId), ...
                [-derived.vMax, derived.vMax], ...
                cfg.rdEnhancedRangeTimeClim, ...
                visibleValue, ...
                'Aliased velocity (m/s)');

            pradar.addFrameLines( ...
                ax3, ...
                targetData.numFrames, ...
                cfg.framePeriod, ...
                cfg.numChirpsPerFrame ...
                    * cfg.chirpPeriod);

            hold(ax3, 'on');

            if ~isempty(candidateTable)

                plot( ...
                    ax3, ...
                    candidateTable.Time_ms, ...
                    candidateTable.AliasedVelocity_mps, ...
                    'wo', ...
                    'LineStyle', 'none', ...
                    'MarkerSize', 5, ...
                    'LineWidth', 0.8);
            end

            if fitInfo.valid

                plot( ...
                    ax3, ...
                    trackTable.Time_ms, ...
                    trackTable.AliasedVelocity_mps, ...
                    'r-o', ...
                    'MarkerFaceColor', 'y', ...
                    'MarkerSize', 6, ...
                    'LineWidth', 1.6);
            end

            hold(ax3, 'off');


        otherwise

            error( ...
                'pradar:InvalidRdProjectionMode', ...
                'Unsupported RD projection mode: %s', ...
                cfg.rdProjectionMode);
    end

    fig4 = figure('Name', 'Figure 4: Track analysis', ...
        'Color', 'w', 'Visible', visibleValue);
    layout = tiledlayout(fig4, 4, 1, ...
        'TileSpacing', 'compact', 'Padding', 'compact'); %#ok<NASGU>

    axRange = nexttile;
    if ~isempty(candidateTable)
        scatter(axRange, candidateTable.Time_ms, candidateTable.Range_m, ...
            24, candidateTable.RelativeStrength_dB, 'filled');
        hold(axRange, 'on');
    end
    if fitInfo.valid
        plot(axRange, trackTable.Time_ms, trackTable.Range_m, 'ro-', ...
            'MarkerFaceColor', 'y', 'MarkerSize', 6, 'LineWidth', 1.4);
        fitTimeMs = linspace( ...
            min(trackTable.Time_ms), max(trackTable.Time_ms), 300);
        plot(axRange, fitTimeMs, ...
            fitInfo.speed * fitTimeMs * 1e-3 + fitInfo.intercept, ...
            'k--', 'LineWidth', 1.3);
        legend(axRange, {'All candidates', 'Selected track'}, ...
            'Location', 'best');
    end
    hold(axRange, 'off');
    grid(axRange, 'on');
    xlabel(axRange, 'Time (ms)');
    ylabel(axRange, 'Range (m)');
    title(axRange, 'Candidate points and fitted track');

    axAlias = nexttile;
    if fitInfo.valid
        plot(axAlias, trackTable.Time_ms, ...
            trackTable.AliasedVelocity_mps, 'o-', ...
            'LineWidth', 1.3, 'MarkerSize', 5);
    end
    grid(axAlias, 'on');
    xlabel(axAlias, 'Time (ms)');
    ylabel(axAlias, 'Aliased velocity (m/s)');
    title(axAlias, 'Aliased velocity along the selected track');
    ylim(axAlias, [-derived.vMax, derived.vMax]);

    axUnwrap = nexttile;
    if fitInfo.valid
        plot(axUnwrap, trackTable.Time_ms, ...
            trackTable.UnwrappedVelocity_mps, 'o-', ...
            'LineWidth', 1.3, 'MarkerSize', 5);
        hold(axUnwrap, 'on');
        yline(axUnwrap, cfg.measuredSpeed, 'k--');
        hold(axUnwrap, 'off');
        title(axUnwrap, sprintf([ ...
            'Unwrapped velocity | RMSE %.1f m/s | ' ...
            'minimum absolute error %.1f m/s'], ...
            metrics.rmse, metrics.minimumAbsoluteError));
    else
        title(axUnwrap, 'Unwrapped velocity');
    end
    grid(axUnwrap, 'on');
    xlabel(axUnwrap, 'Time (ms)');
    ylabel(axUnwrap, 'Unwrapped velocity (m/s)');
    ylim(axUnwrap, [cfg.unwrapSpeedMin, cfg.unwrapSpeedMax]);

    axStrength = nexttile;
    if fitInfo.valid
        plot(axStrength, trackTable.Time_ms, ...
            trackTable.RelativeStrength_dB, 'o-', ...
            'LineWidth', 1.3, 'MarkerSize', 5);
    end
    grid(axStrength, 'on');
    xlabel(axStrength, 'Time (ms)');
    ylabel(axStrength, 'RD enhancement (dB)');
    title(axStrength, 'Selected-track RD enhancement');

    figures = struct( ...
        'rawRangeTime', ancestor(ax1, 'figure'), ...
        'enhancedRangeTime', ancestor(ax2, 'figure'), ...
        'rdCompressedTrack', ancestor(ax3, 'figure'), ...
        'trackAnalysis', fig4);
end
