clear;
clc;
close all;

%% =========================================================
%  1. 原始数据与雷达参数
% ==========================================================

cfg.numSamples = 64;               % 每个Chirp ADC采样点数
cfg.numChirpsPerFrame = 256;       % 每个物理帧Chirp数
cfg.numRx = 8;                     % 接收通道数
cfg.numTx = 1;                     % 当前数据为单发射
cfg.rangeFftSize = 256;            % 距离FFT点数
cfg.dopplerFftSize = 128;

cfg.adcSampleRate = 10e6;          % Hz
cfg.slope = 60.01e12;              % Hz/s
cfg.startFreq = 77e9;              % Hz

cfg.chirpPeriod = 12e-6;           % s
cfg.framePeriod = 3.5e-3;          % s

cfg.c = 3e8;

%% =========================================================
%  2. 距离-Doppler处理参数
% ==========================================================

cfg.winSize = 16;
cfg.winStep = 16;

% 只保留高速有模糊速度区域
cfg.highSpeedMin = 0;             % m/s

% 候选目标距离范围
cfg.candidateRangeMin = 0.3;       % m
cfg.candidateRangeMax = 6.0;       % m

% 每个窗口最多保留多少个距离候选
cfg.maxCandidatesPerWindow = 5;

% 候选点必须高于枪击前背景的幅度
cfg.candidateThresholdDb = 3.0;    % dB

% 同一窗口候选点之间的最小距离间隔
cfg.minCandidateSeparation = 0.30; % m

% 距离轮廓平滑点数
cfg.rangeSmoothBins = 3;

%% =========================================================
%  3. 轨迹筛选与速度拟合参数
% ==========================================================

% 拟合时允许的表观径向速度范围
cfg.fitSpeedMin = 300;             % m/s
cfg.fitSpeedMax = 700;             % m/s

% 候选点距拟合轨迹小于该值时视为内点
cfg.trackTolerance = 0.55;         % m

% 形成有效轨迹至少需要覆盖的窗口数量
cfg.minTrackWindows = 6;

% 过早的枪口耦合可不参与轨迹拟合
cfg.trackStartTimeMs = 1.60;       % ms

% 解模糊速度合理范围
cfg.unwrapSpeedMin = 250;          % m/s
cfg.unwrapSpeedMax = 750;          % m/s

% =========================================================
% 本发目标的实测速度先验
% =========================================================

cfg.measuredSpeed = 432.09819;     % m/s

% 实测速度并非严格径向真值，因此采用软约束。
cfg.measuredSpeedStd = 35.0;       % m/s
cfg.distanceFitSpeedStd = 50.0;    % m/s
cfg.unwrapContinuityStd = 25.0;    % m/s

% 全局动态规划解模糊的代价权重。
cfg.unwrapMeasuredWeight = 1.00;
cfg.unwrapFitWeight = 0.45;
cfg.unwrapContinuityWeight = 0.80;

% 模糊数搜索范围。
cfg.ambiguityNumberMin = -4;
cfg.ambiguityNumberMax = 8;

% 在距离轨迹关联阶段使用实测速度折叠值作为软约束。
cfg.measuredAliasTolerance = 60.0; % m/s
cfg.measuredAliasCostWeight = 0.30;
cfg.trackStrengthCostWeight = 0.10;

%% =========================================================
%  4. 物理帧范围
% ==========================================================

% 枪击前无目标背景帧
cfg.backgroundFrameStart = 170;
cfg.backgroundFrameEnd = 176;

% 需要分析的目标帧
cfg.targetFrameStart = 178;
cfg.targetFrameEnd = 180;

%% =========================================================
%  5. 图像显示参数
% ==========================================================

cfg.displayRangeMin = 0;
cfg.displayRangeMax = 10;

cfg.rawDynamicRangeDb = 35;

cfg.chirpEnhancedClim = [0, 15];
cfg.highSpeedClim = [0, 35];

%% =========================================================
%  6. 二维RD连续变化GIF参数
% ==========================================================

% 方案A：GIF只显示每个滑窗的完整二维RD背景增强图，
% 不叠加候选点，也不叠加最终轨迹。
cfg.generateRdGif = true;

% GIF每帧停留时间
cfg.rdGifDelayTime = 0.15;         % s

% 所有GIF帧固定使用同一颜色范围，避免播放时闪烁
cfg.rdGifClim = [0, 35];           % dB

% GIF显示距离范围
cfg.rdGifRangeMin = 0;             % m
cfg.rdGifRangeMax = 10;            % m

% GIF中间PNG分辨率
cfg.rdGifResolution = 120;

% false表示生成过程中不额外弹出GIF绘图窗口
cfg.rdGifVisible = false;

%% =========================================================
%  7. 保存结果
% ==========================================================

cfg.saveResults = false;

%% =========================================================
%  8. 选择DCA1000原始数据文件
% ==========================================================

[fileName, filePath] = uigetfile( ...
    {'*.bin', 'DCA1000原始数据文件 (*.bin)'}, ...
    '选择需要分析的Raw文件');

if isequal(fileName, 0)
    error('未选择数据文件。');
end

binPath = fullfile(filePath, fileName);

if cfg.numTx ~= 1
    error('当前脚本按照单Tx数据格式编写，numTx必须为1。');
end

%% =========================================================
%  9. 文件和帧信息
% ==========================================================

cfg.complexSamplesPerFrame = ...
    cfg.numSamples ...
    * cfg.numChirpsPerFrame ...
    * cfg.numRx;

cfg.bytesPerFrame = ...
    cfg.complexSamplesPerFrame * 4;

cfg.uint16PerFrame = ...
    cfg.complexSamplesPerFrame * 2;

fileInfo = dir(binPath);

if isempty(fileInfo)
    error('无法读取文件信息：%s', binPath);
end

totalFramesInFile = ...
    floor(fileInfo.bytes / cfg.bytesPerFrame);

remainingBytes = ...
    mod(fileInfo.bytes, cfg.bytesPerFrame);

fprintf('========================================\n');
fprintf('数据文件：%s\n', binPath);
fprintf('文件大小：%d Bytes，%.3f MiB\n', ...
    fileInfo.bytes, fileInfo.bytes / 1024^2);
fprintf('单帧大小：%d Bytes\n', cfg.bytesPerFrame);
fprintf('完整物理帧数：%d\n', totalFramesInFile);
fprintf('尾部剩余字节：%d\n', remainingBytes);
fprintf('========================================\n');

validateFrameRange( ...
    cfg.backgroundFrameStart, ...
    cfg.backgroundFrameEnd, ...
    totalFramesInFile, ...
    '背景帧');

validateFrameRange( ...
    cfg.targetFrameStart, ...
    cfg.targetFrameEnd, ...
    totalFramesInFile, ...
    '目标帧');

%% =========================================================
%  10. 距离轴与速度轴
% ==========================================================

derived.rangeBinSpacing = ...
    cfg.c * cfg.adcSampleRate ...
    / (2 * cfg.slope * cfg.rangeFftSize);

derived.rangeAxis = ...
    (0:cfg.rangeFftSize - 1) ...
    * derived.rangeBinSpacing;

adcDuration = ...
    cfg.numSamples / cfg.adcSampleRate;

bandwidth = ...
    cfg.slope * adcDuration;

centerFreq = ...
    cfg.startFreq + bandwidth / 2;

derived.lambda = ...
    cfg.c / centerFreq;

derived.deltaV = ...
    derived.lambda ...
    / (2 * cfg.winSize * cfg.chirpPeriod);

derived.deltaVDisplay = ...
    derived.lambda ...
    / (2 * cfg.dopplerFftSize * cfg.chirpPeriod);

derived.velocityAxis = ...
    (-cfg.dopplerFftSize / 2 : cfg.dopplerFftSize / 2 - 1) ...
    * derived.deltaVDisplay;

derived.vMax = ...
    cfg.winSize / 2 * derived.deltaV;

derived.velocityPeriod = ...
    2 * derived.vMax;

derived.measuredAliasedSpeed = ...
    wrapVelocity(cfg.measuredSpeed, derived.vMax);

derived.highSpeedMask = ...
    abs(derived.velocityAxis) >= cfg.highSpeedMin;

derived.selectedVelocityAxis = ...
    derived.velocityAxis(derived.highSpeedMask);

derived.windowsPerFrame = ...
    floor( ...
        (cfg.numChirpsPerFrame - cfg.winSize) ...
        / cfg.winStep) + 1;

derived.rangeWindow = reshape( ...
    single(hann(cfg.numSamples)), ...
    cfg.numSamples, 1, 1);

derived.dopplerWindow = reshape( ...
    single(hann(cfg.winSize)).', ...
    1, cfg.winSize, 1);

if ~any(derived.highSpeedMask)
    error('高速速度门限过大，没有速度单元被保留。');
end

fprintf('距离单元间隔：%.4f m\n', ...
    derived.rangeBinSpacing);

fprintf('速度分辨率：%.3f m/s\n', ...
    derived.deltaV);

fprintf('最大不模糊速度：±%.3f m/s\n', ...
    derived.vMax);

fprintf('速度模糊周期：%.3f m/s\n', ...
    derived.velocityPeriod);

fprintf('实测速度：%.5f m/s\n', ...
    cfg.measuredSpeed);

fprintf('实测速度对应有模糊速度：%+.3f m/s\n', ...
    derived.measuredAliasedSpeed);

fprintf('高速速度门限：|v| >= %.1f m/s\n', ...
    cfg.highSpeedMin);

fprintf('每个物理帧窗口数：%d\n', ...
    derived.windowsPerFrame);

fprintf('被保留的有模糊速度单元：\n');
disp(derived.selectedVelocityAxis);

%% =========================================================
%  11. 打开数据文件
% ==========================================================

fid = fopen(binPath, 'rb', 'ieee-le');

if fid < 0
    error('无法打开数据文件：%s', binPath);
end

cleanupObj = onCleanup(@() fclose(fid));

%% =========================================================
%  12. 处理枪击前背景帧
% ==========================================================

fprintf('\n正在处理背景物理帧 %d～%d……\n', ...
    cfg.backgroundFrameStart, ...
    cfg.backgroundFrameEnd);

backgroundData = processFrameRange( ...
    fid, ...
    cfg.backgroundFrameStart, ...
    cfg.backgroundFrameEnd, ...
    cfg, ...
    derived);

%% =========================================================
%  13. 处理目标帧
% ==========================================================

fprintf('\n正在处理目标物理帧 %d～%d……\n', ...
    cfg.targetFrameStart, ...
    cfg.targetFrameEnd);

targetData = processFrameRange( ...
    fid, ...
    cfg.targetFrameStart, ...
    cfg.targetFrameEnd, ...
    cfg, ...
    derived);

%% =========================================================
%  14. 使用枪击前数据建立背景
% ==========================================================

% 每个距离单元的逐Chirp背景
rangeBackgroundDb = median( ...
    backgroundData.rangeTimeDb, ...
    2, ...
    'omitnan');

% 逐Chirp距离图仍采用原来的dB域背景增强，仅用于Figure 2显示
rangeTimeEnhanced = ...
    targetData.rangeTimeDb ...
    - rangeBackgroundDb;

% =========================================================
% 完整二维RD功率背景增强
%
% 1. 每个背景窗口先得到线性二维RD功率：
%       P(r,v,w) = sum_rx |X(r,v,w,rx)|^2
%
% 2. 对固定的距离-速度单元沿背景窗口维取中位数：
%       P_bg(r,v) = median_w P_bgWindow(r,v,w)
%
% 3. 目标窗口与背景功率作比值并转换为dB：
%       E(r,v,w) = 10log10(P_target / P_bg)
% =========================================================

powerFloor = single(1e-12);

% 完整二维RD线性功率背景：距离 × 有模糊速度
rdBackgroundPower = median( ...
    backgroundData.rdPowerCube, ...
    3, ...
    'omitnan');

% 目标帧完整二维RD功率相对背景的增强量
% 维度：距离 × 有模糊速度 × 窗口
rdEnhancedDb = ...
    10 * log10( ...
        (targetData.rdPowerCube + powerFloor) ...
        ./ (rdBackgroundPower + powerFloor));

% 只在指定的高速有模糊速度区域内进行压缩。
% 先完成每个距离-速度单元的背景增强，再沿速度维取最大值。
highSpeedEnhancedCube = ...
    rdEnhancedDb(:, derived.highSpeedMask, :);

[highSpeedEnhanced, maxVelocityIdx] = max( ...
    highSpeedEnhancedCube, ...
    [], ...
    2);

% max后维度为：距离 × 1 × 窗口，恢复为：距离 × 窗口
highSpeedEnhanced = reshape( ...
    highSpeedEnhanced, ...
    cfg.rangeFftSize, ...
    []);

maxVelocityIdx = reshape( ...
    maxVelocityIdx, ...
    cfg.rangeFftSize, ...
    []);

% 保存每个距离单元在背景增强后取得最大值时的有模糊速度
highSpeedVelocityMap = nan( ...
    size(highSpeedEnhanced), ...
    'single');

for windowIdx = 1:size(highSpeedEnhanced, 2)
    highSpeedVelocityMap(:, windowIdx) = single( ...
        derived.selectedVelocityAxis( ...
        maxVelocityIdx(:, windowIdx)));
end

%% =========================================================
%  15. 生成二维RD连续变化GIF
% ==========================================================

[~, gifBaseName, ~] = fileparts(fileName);

rdGifOutputPath = fullfile( ...
    filePath, ...
    [gifBaseName, '_2D_RD_evolution.gif']);

if cfg.generateRdGif

    fprintf('\n正在生成二维RD连续变化GIF……\n');

    createRdEvolutionGif( ...
        rdEnhancedDb, ...
        targetData, ...
        derived, ...
        cfg, ...
        rdGifOutputPath);

    fprintf('[完成] 二维RD连续变化GIF：\n%s\n', ...
        rdGifOutputPath);
end

%% =========================================================
%  16. 每个窗口提取多个高速候选点
% ==========================================================

candidateTable = extractHighSpeedCandidates( ...
    highSpeedEnhanced, ...
    highSpeedVelocityMap, ...
    targetData, ...
    derived.rangeAxis, ...
    cfg);

fprintf('\n========================================\n');
fprintf('所有高速候选点数量：%d\n', ...
    height(candidateTable));
fprintf('========================================\n');

if ~isempty(candidateTable)
    disp(candidateTable);
else
    fprintf('没有候选点通过当前门限。\n');
end

%% =========================================================
%  17. 从所有候选点中筛选连续高速轨迹
% ==========================================================

[trackTable, fitInfo] = selectRobustTrack( ...
    candidateTable, ...
    cfg, ...
    derived);

if fitInfo.valid

    trackTable = unwrapTrackVelocity( ...
        trackTable, ...
        derived.vMax, ...
        fitInfo.speed, ...
        cfg);

    validUnwrapped = ...
        isfinite( ...
        trackTable.UnwrappedVelocity_mps);

    if any(validUnwrapped)

        velocityError = ...
            trackTable.UnwrappedVelocity_mps( ...
            validUnwrapped) ...
            - cfg.measuredSpeed;

        fitInfo.meanUnwrappedSpeed = ...
            mean( ...
            trackTable.UnwrappedVelocity_mps( ...
            validUnwrapped));

        fitInfo.unwrapSpeedStd = ...
            std( ...
            trackTable.UnwrappedVelocity_mps( ...
            validUnwrapped));

        fitInfo.unwrapSpeedMae = ...
            mean(abs(velocityError));

        fitInfo.unwrapSpeedRmse = ...
            sqrt(mean(velocityError.^2));

    else

        fitInfo.meanUnwrappedSpeed = NaN;
        fitInfo.unwrapSpeedStd = NaN;
        fitInfo.unwrapSpeedMae = NaN;
        fitInfo.unwrapSpeedRmse = NaN;
    end

    fprintf('\n========================================\n');
    fprintf('高速目标轨迹拟合结果\n');
    fprintf('轨迹点数量：%d\n', height(trackTable));
    fprintf('表观径向速度：%.2f m/s\n', fitInfo.speed);
    fprintf('拟合距离截距：%.3f m\n', fitInfo.intercept);
    fprintf('距离拟合RMSE：%.3f m\n', fitInfo.rmse);
    fprintf('实测速度：%.5f m/s\n', ...
        cfg.measuredSpeed);
    fprintf('解模糊平均速度：%.2f m/s\n', ...
        fitInfo.meanUnwrappedSpeed);
    fprintf('解模糊速度标准差：%.2f m/s\n', ...
        fitInfo.unwrapSpeedStd);
    fprintf('解模糊速度相对实测速度MAE：%.2f m/s\n', ...
        fitInfo.unwrapSpeedMae);
    fprintf('解模糊速度相对实测速度RMSE：%.2f m/s\n', ...
        fitInfo.unwrapSpeedRmse);
    fprintf('========================================\n');

    disp(trackTable);

else
    warning( ...
        ['没有找到满足当前约束的连续高速轨迹。' ...
         '请适当降低candidateThresholdDb，' ...
         '或增大trackTolerance。']);
end

%% =========================================================
%  18. 绘制逐Chirp原始距离-时间图
% ==========================================================

finiteRaw = ...
    targetData.rangeTimeDb( ...
    isfinite(targetData.rangeTimeDb));

rawMaxDb = max(finiteRaw);

ax1 = drawSegmentedMap( ...
    targetData.chirpTimeMs, ...
    derived.rangeAxis, ...
    targetData.rangeTimeDb, ...
    cfg.numChirpsPerFrame, ...
    targetData.numFrames, ...
    '逐Chirp原始距离-时间图', ...
    sprintf( ...
        '逐Chirp原始距离-时间图：物理帧%d～%d', ...
        cfg.targetFrameStart, ...
        cfg.targetFrameEnd), ...
    [cfg.displayRangeMin, cfg.displayRangeMax], ...
    [rawMaxDb - cfg.rawDynamicRangeDb, rawMaxDb]);

addFrameLines( ...
    ax1, ...
    targetData.numFrames, ...
    cfg.framePeriod, ...
    cfg.numChirpsPerFrame * cfg.chirpPeriod);

%% =========================================================
%  19. 绘制背景扣除逐Chirp距离-时间图
% ==========================================================

ax2 = drawSegmentedMap( ...
    targetData.chirpTimeMs, ...
    derived.rangeAxis, ...
    rangeTimeEnhanced, ...
    cfg.numChirpsPerFrame, ...
    targetData.numFrames, ...
    '背景扣除逐Chirp距离-时间图', ...
    sprintf( ...
        '背景扣除逐Chirp距离-时间图：物理帧%d～%d', ...
        cfg.targetFrameStart, ...
        cfg.targetFrameEnd), ...
    [cfg.displayRangeMin, cfg.displayRangeMax], ...
    cfg.chirpEnhancedClim);

addFrameLines( ...
    ax2, ...
    targetData.numFrames, ...
    cfg.framePeriod, ...
    cfg.numChirpsPerFrame * cfg.chirpPeriod);

%% =========================================================
%  20. 绘制高速目标距离-时间图
% ==========================================================

ax3 = drawSegmentedMap( ...
    targetData.windowTimeMs, ...
    derived.rangeAxis, ...
    highSpeedEnhanced, ...
    derived.windowsPerFrame, ...
    targetData.numFrames, ...
    '高速目标距离-时间图', ...
    sprintf( ...
        '高速距离-时间图：物理帧%d～%d，|v|≥%.0f m/s', ...
        cfg.targetFrameStart, ...
        cfg.targetFrameEnd, ...
        cfg.highSpeedMin), ...
    [cfg.displayRangeMin, cfg.displayRangeMax], ...
    cfg.highSpeedClim);

addFrameLines( ...
    ax3, ...
    targetData.numFrames, ...
    cfg.framePeriod, ...
    cfg.numChirpsPerFrame * cfg.chirpPeriod);

hold(ax3, 'on');

% 所有候选点
if ~isempty(candidateTable)

    plot( ...
        ax3, ...
        candidateTable.Time_ms, ...
        candidateTable.Range_m, ...
        'wo', ...
        'LineStyle', 'none', ...
        'MarkerSize', 6, ...
        'LineWidth', 1.0);
end

% 最终筛选出的连续轨迹
if fitInfo.valid

    plot( ...
        ax3, ...
        trackTable.Time_ms, ...
        trackTable.Range_m, ...
        'r-o', ...
        'MarkerFaceColor', 'y', ...
        'MarkerSize', 7, ...
        'LineWidth', 1.8);

    fitTimeLineMs = linspace( ...
        min(trackTable.Time_ms), ...
        max(trackTable.Time_ms), ...
        300);

    fitRangeLine = ...
        fitInfo.speed * fitTimeLineMs * 1e-3 ...
        + fitInfo.intercept;

    plot( ...
        ax3, ...
        fitTimeLineMs, ...
        fitRangeLine, ...
        'w--', ...
        'LineWidth', 1.5);
end

hold(ax3, 'off');

%% =========================================================
%  21. 绘制候选点与最终轨迹趋势
% ==========================================================

figure( ...
    'Name', '高速目标轨迹分析', ...
    'Color', 'w');

layout = tiledlayout(4, 1);
layout.TileSpacing = 'compact';
layout.Padding = 'compact';

% ---------------------------------------------------------
% 距离趋势
% ----------------------------------------------------------

axRange = nexttile;

if ~isempty(candidateTable)

    scatter( ...
        axRange, ...
        candidateTable.Time_ms, ...
        candidateTable.Range_m, ...
        25, ...
        candidateTable.RelativeStrength_dB, ...
        'filled');

    hold(axRange, 'on');
end

if fitInfo.valid

    plot( ...
        axRange, ...
        trackTable.Time_ms, ...
        trackTable.Range_m, ...
        'ro-', ...
        'MarkerFaceColor', 'y', ...
        'MarkerSize', 6, ...
        'LineWidth', 1.5);

    fitTimeLineMs = linspace( ...
        min(trackTable.Time_ms), ...
        max(trackTable.Time_ms), ...
        300);

    plot( ...
        axRange, ...
        fitTimeLineMs, ...
        fitInfo.speed * fitTimeLineMs * 1e-3 ...
        + fitInfo.intercept, ...
        'k--', ...
        'LineWidth', 1.4);

    legend( ...
        axRange, ...
        {'所有候选点', '连续轨迹'}, ...
        'Location', 'best');
end

hold(axRange, 'off');

grid(axRange, 'on');
xlabel(axRange, 'Time (ms)');
ylabel(axRange, 'Range (m)');
title(axRange, '高速候选点与连续轨迹');

% ---------------------------------------------------------
% 有模糊速度趋势
% ----------------------------------------------------------

axAlias = nexttile;

if fitInfo.valid

    plot( ...
        axAlias, ...
        trackTable.Time_ms, ...
        trackTable.AliasedVelocity_mps, ...
        'o-', ...
        'LineWidth', 1.4, ...
        'MarkerSize', 6);
end

grid(axAlias, 'on');
xlabel(axAlias, 'Time (ms)');
ylabel(axAlias, 'Aliased velocity (m/s)');
title(axAlias, '连续轨迹有模糊速度');

ylim(axAlias, ...
    [-derived.vMax, derived.vMax]);

% ---------------------------------------------------------
% 解模糊速度趋势
% ----------------------------------------------------------

axUnwrap = nexttile;

if fitInfo.valid

    plot( ...
        axUnwrap, ...
        trackTable.Time_ms, ...
        trackTable.UnwrappedVelocity_mps, ...
        'o-', ...
        'LineWidth', 1.4, ...
        'MarkerSize', 6);

    hold(axUnwrap, 'on');

    yline( ...
        axUnwrap, ...
        fitInfo.speed, ...
        'k--');

    text( ...
        axUnwrap, ...
        0.98, ...
        0.90, ...
        sprintf( ...
        '相对实测速度 RMSE: %.1f m/s', ...
        fitInfo.unwrapSpeedRmse), ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', ...
        'FontSize', 10, ...
        'BackgroundColor', 'w', ...
        'Margin', 3);

    hold(axUnwrap, 'off');
end

grid(axUnwrap, 'on');
xlabel(axUnwrap, 'Time (ms)');
ylabel(axUnwrap, 'Unwrapped velocity (m/s)');
title(axUnwrap, '连续轨迹解模糊速度');

ylim(axUnwrap, ...
    [cfg.unwrapSpeedMin, cfg.unwrapSpeedMax]);

% ---------------------------------------------------------
% 连续轨迹相对背景强度
% ----------------------------------------------------------

axStrength = nexttile;

if fitInfo.valid

    plot( ...
        axStrength, ...
        trackTable.Time_ms, ...
        trackTable.RelativeStrength_dB, ...
        'o-', ...
        'LineWidth', 1.4, ...
        'MarkerSize', 6);
end

grid(axStrength, 'on');
xlabel(axStrength, 'Time (ms)');
ylabel(axStrength, 'Relative strength (dB)');
title(axStrength, '连续轨迹相对背景强度');

%% =========================================================
%  22. 保存结果
% ==========================================================

if cfg.saveResults

    [~, baseName, ~] = fileparts(fileName);

    matOutputPath = fullfile( ...
        filePath, ...
        [baseName, '_high_speed_analysis.mat']);

    candidateCsvPath = fullfile( ...
        filePath, ...
        [baseName, '_all_candidates.csv']);

    trackCsvPath = fullfile( ...
        filePath, ...
        [baseName, '_selected_track.csv']);

    save( ...
        matOutputPath, ...
        'cfg', ...
        'derived', ...
        'backgroundData', ...
        'targetData', ...
        'rangeTimeEnhanced', ...
        'highSpeedEnhanced', ...
        'highSpeedVelocityMap', ...
        'rdBackgroundPower', ...
        'rdEnhancedDb', ...
        'rdGifOutputPath', ...
        'candidateTable', ...
        'trackTable', ...
        'fitInfo');

    writetable( ...
        candidateTable, ...
        candidateCsvPath);

    if fitInfo.valid
        writetable( ...
            trackTable, ...
            trackCsvPath);
    end

    fprintf('\n结果已保存：\n');
    fprintf('%s\n', matOutputPath);
    fprintf('%s\n', candidateCsvPath);

    if fitInfo.valid
        fprintf('%s\n', trackCsvPath);
    end
end

fprintf('\n全部处理完成。\n');

%% =========================================================
%  局部函数：生成二维RD连续变化GIF
% ==========================================================

function createRdEvolutionGif( ...
        rdEnhancedDb, ...
        targetData, ...
        derived, ...
        cfg, ...
        outputPath)

    numWindows = size(rdEnhancedDb, 3);

    if numWindows < 1
        warning('目标帧中没有可用于生成GIF的RD窗口。');
        return;
    end

    if exist(outputPath, 'file')
        delete(outputPath);
    end

    if cfg.rdGifVisible
        figureVisibility = 'on';
    else
        figureVisibility = 'off';
    end

    gifFigure = figure( ...
        'Name', '二维RD连续变化GIF', ...
        'Color', 'w', ...
        'Visible', figureVisibility, ...
        'Position', [100, 100, 960, 760]);

    gifAxes = axes(gifFigure);

    imageHandle = imagesc( ...
        gifAxes, ...
        derived.velocityAxis, ...
        derived.rangeAxis, ...
        double(rdEnhancedDb(:, :, 1)));

    gifAxes.YDir = 'normal';
    gifAxes.Box = 'on';

    xlabel(gifAxes, 'Aliased velocity (m/s)');
    ylabel(gifAxes, 'Range (m)');

    xlim(gifAxes, [ ...
        min(derived.velocityAxis), ...
        max(derived.velocityAxis)]);

    ylim(gifAxes, [ ...
        cfg.rdGifRangeMin, ...
        cfg.rdGifRangeMax]);

    caxis(gifAxes, cfg.rdGifClim);
    colormap(gifAxes, turbo);

    colorBarHandle = colorbar(gifAxes);
    ylabel(colorBarHandle, ...
        'RD background enhancement (dB)');

    temporaryPngPath = [tempname, '.png'];

    cleanupObject = onCleanup( ...
        @() cleanupRdGifResources( ...
        gifFigure, temporaryPngPath)); %#ok<NASGU>

    for globalWindowIdx = 1:numWindows

        currentPhysicalFrame = ...
            targetData.windowPhysicalFrame(globalWindowIdx);

        currentWindowInFrame = ...
            targetData.windowIndexInFrame(globalWindowIdx);

        currentCenterTimeMs = ...
            targetData.windowTimeMs(globalWindowIdx);

        chirpStart = ...
            (currentWindowInFrame - 1) ...
            * cfg.winStep + 1;

        chirpEnd = ...
            chirpStart + cfg.winSize - 1;

        set( ...
            imageHandle, ...
            'CData', ...
            double(rdEnhancedDb(:, :, globalWindowIdx)));

        % 使用两行标题，避免字符串中的\n被直接显示出来
        title( ...
            gifAxes, ...
            { ...
                '二维FFT背景增强RD连续变化', ...
                sprintf( ...
                    ['物理帧 %d | 窗口 %d/%d | ' ...
                     'Chirp %d～%d | 中心时刻 %.3f ms'], ...
                    currentPhysicalFrame, ...
                    currentWindowInFrame, ...
                    derived.windowsPerFrame, ...
                    chirpStart, ...
                    chirpEnd, ...
                    currentCenterTimeMs) ...
            }, ...
            'FontWeight', 'bold', ...
            'Interpreter', 'none');

        drawnow;

        print( ...
            gifFigure, ...
            temporaryPngPath, ...
            '-dpng', ...
            sprintf('-r%d', cfg.rdGifResolution));

        rgbFrame = imread(temporaryPngPath);

        [indexedFrame, colorMap] = ...
            rgb2ind(rgbFrame, 256, 'nodither');

        if globalWindowIdx == 1

            imwrite( ...
                indexedFrame, ...
                colorMap, ...
                outputPath, ...
                'gif', ...
                'LoopCount', Inf, ...
                'DelayTime', cfg.rdGifDelayTime);

        else

            imwrite( ...
                indexedFrame, ...
                colorMap, ...
                outputPath, ...
                'gif', ...
                'WriteMode', 'append', ...
                'DelayTime', cfg.rdGifDelayTime);
        end

        fprintf( ...
            '  GIF帧 %d / %d：物理帧%d，窗口%d\n', ...
            globalWindowIdx, ...
            numWindows, ...
            currentPhysicalFrame, ...
            currentWindowInFrame);
    end
end

%% =========================================================
%  局部函数：清理GIF临时资源
% ==========================================================

function cleanupRdGifResources( ...
        gifFigure, ...
        temporaryPngPath)

    if exist(temporaryPngPath, 'file')
        delete(temporaryPngPath);
    end

    if isgraphics(gifFigure)
        close(gifFigure);
    end
end

%% =========================================================
%  局部函数：验证帧范围
% ==========================================================

function validateFrameRange( ...
        frameStart, ...
        frameEnd, ...
        totalFrames, ...
        rangeName)

    if frameStart < 1 ...
            || frameEnd < frameStart ...
            || frameEnd > totalFrames

        error( ...
            '%s范围无效：%d～%d，文件总帧数为%d。', ...
            rangeName, ...
            frameStart, ...
            frameEnd, ...
            totalFrames);
    end
end

%% =========================================================
%  局部函数：处理一个连续物理帧区间
% ==========================================================

function output = processFrameRange( ...
        fid, ...
        frameStart, ...
        frameEnd, ...
        cfg, ...
        derived)

    numFrames = ...
        frameEnd - frameStart + 1;

    totalChirps = ...
        numFrames * cfg.numChirpsPerFrame;

    totalWindows = ...
        numFrames * derived.windowsPerFrame;

    output.rangeTimeDb = nan( ...
        cfg.rangeFftSize, ...
        totalChirps, ...
        'single');

    output.chirpTimeMs = nan( ...
        1, totalChirps);

    % 完整二维RD线性功率：
    % 距离 × 有模糊速度 × 窗口
    output.rdPowerCube = nan( ...
        cfg.rangeFftSize, ...
        cfg.dopplerFftSize, ...
        totalWindows, ...
        'single');

    output.windowTimeMs = nan( ...
        1, totalWindows);

    output.windowPhysicalFrame = nan( ...
        1, totalWindows);

    output.windowIndexInFrame = nan( ...
        1, totalWindows);

    output.numFrames = numFrames;

    chirpColumn = 1;
    windowColumn = 1;

    for frameIdx = frameStart:frameEnd

        fprintf('  正在处理物理帧 %d / %d\n', ...
            frameIdx, frameEnd);

        byteOffset = ...
            (frameIdx - 1) ...
            * cfg.bytesPerFrame;

        seekStatus = ...
            fseek(fid, byteOffset, 'bof');

        if seekStatus ~= 0
            error('无法跳转到物理帧%d。', frameIdx);
        end

        rawData = fread( ...
            fid, ...
            cfg.uint16PerFrame, ...
            'uint16=>double');

        if numel(rawData) < cfg.uint16PerFrame
            error('物理帧%d数据不完整。', frameIdx);
        end

        negativeMask = ...
            rawData >= 2^15;

        rawData(negativeMask) = ...
            rawData(negativeMask) - 2^16;

        adcComplex = complex( ...
            rawData(1:2:end), ...
            rawData(2:2:end));

        % 原始排列：
        % Sample × RX × Chirp
        adcComplex = reshape( ...
            adcComplex, ...
            cfg.numSamples, ...
            cfg.numRx, ...
            cfg.numChirpsPerFrame);

        % 转换为：
        % Sample × Chirp × RX
        adcFrame = permute( ...
            adcComplex, ...
            [1, 3, 2]);

        adcFrame = single(adcFrame);

        %% 逐Chirp距离FFT

        rangeFftAll = fft( ...
            adcFrame .* derived.rangeWindow, ...
            cfg.rangeFftSize, ...
            1);

        rangeAmplitude = sum( ...
            abs(rangeFftAll), ...
            3);

        rangeAmplitudeDb = ...
            20 * log10( ...
                rangeAmplitude ...
                + single(1e-6));

        chirpColumnEnd = ...
            chirpColumn ...
            + cfg.numChirpsPerFrame - 1;

        chirpColumns = ...
            chirpColumn:chirpColumnEnd;

        output.rangeTimeDb(:, chirpColumns) = ...
            rangeAmplitudeDb;

        relativeFrameIdx = ...
            frameIdx - frameStart;

        output.chirpTimeMs(chirpColumns) = ...
            (relativeFrameIdx ...
            * cfg.framePeriod ...
            + (0:cfg.numChirpsPerFrame - 1) ...
            * cfg.chirpPeriod) ...
            * 1e3;

        chirpColumn = ...
            chirpColumnEnd + 1;

        %% 每个窗口计算RD图

        for localWindowIdx = ...
                1:derived.windowsPerFrame

            chirpStart = ...
                (localWindowIdx - 1) ...
                * cfg.winStep + 1;

            chirpEnd = ...
                chirpStart ...
                + cfg.winSize - 1;

            chirpIndices = ...
                chirpStart:chirpEnd;

            adcWindow = ...
                adcFrame(:, chirpIndices, :);

            % 慢时间复数去均值
            adcWindow = ...
                adcWindow ...
                - mean(adcWindow, 2);

            rangeFftWindow = fft( ...
                adcWindow ...
                .* derived.rangeWindow, ...
                cfg.rangeFftSize, ...
                1);

            rangeDoppler = fftshift( ...
                fft( ...
                    rangeFftWindow ...
                    .* derived.dopplerWindow, ...
                    cfg.dopplerFftSize, ...
                    2), ...
                2);

            % 对所有接收通道进行功率非相干累加。
            % 保留线性功率，不在这里转换为dB，也不提前压缩速度维。
            rdPower = sum( ...
                abs(rangeDoppler).^2, ...
                3);

            output.rdPowerCube( ...
                :, :, windowColumn) = ...
                single(rdPower);

            windowCenterChirp = ...
                (chirpStart - 1) ...
                + (cfg.winSize - 1) / 2;

            output.windowTimeMs( ...
                windowColumn) = ...
                (relativeFrameIdx ...
                * cfg.framePeriod ...
                + windowCenterChirp ...
                * cfg.chirpPeriod) ...
                * 1e3;

            output.windowPhysicalFrame( ...
                windowColumn) = ...
                frameIdx;

            output.windowIndexInFrame( ...
                windowColumn) = ...
                localWindowIdx;

            windowColumn = ...
                windowColumn + 1;
        end
    end
end

%% =========================================================
%  局部函数：提取每个窗口的多个局部候选点
% ==========================================================

function candidateTable = ...
        extractHighSpeedCandidates( ...
        highSpeedEnhanced, ...
        highSpeedVelocityMap, ...
        targetData, ...
        rangeAxis, ...
        cfg)

    globalWindow = [];
    physicalFrame = [];
    windowInFrame = [];
    timeMs = [];
    rangeM = [];
    aliasedVelocity = [];
    relativeStrength = [];
    rangeBin = [];

    rangeGate = ...
        rangeAxis(:) >= cfg.candidateRangeMin ...
        & rangeAxis(:) <= cfg.candidateRangeMax;

    numWindows = ...
        size(highSpeedEnhanced, 2);

    for windowIdx = 1:numWindows

        profile = double( ...
            highSpeedEnhanced(:, windowIdx));

        profileSmooth = movmean( ...
            profile, ...
            cfg.rangeSmoothBins, ...
            'omitnan');

        profileSmooth(~rangeGate) = -Inf;

        numBins = numel(profileSmooth);
        
        validBins = find(rangeGate);
        
        if numel(validBins) < 3
            continue;
        end
        
        firstValidBin = validBins(1);
        lastValidBin = validBins(end);
        
        isLocalPeak = false(numBins, 1);
        
        % 不允许候选点位于距离搜索区的两个边界
        innerBins = ...
            (firstValidBin + 1):(lastValidBin - 1);
        
        isLocalPeak(innerBins) = ...
            profileSmooth(innerBins) ...
            >= profileSmooth(innerBins - 1) ...
            & profileSmooth(innerBins) ...
            > profileSmooth(innerBins + 1);
        
        peakIndices = find( ...
            isLocalPeak ...
            & profileSmooth ...
            >= cfg.candidateThresholdDb);

        if isempty(peakIndices)
            continue;
        end

        [~, sortOrder] = sort( ...
            profileSmooth(peakIndices), ...
            'descend');

        peakIndices = ...
            peakIndices(sortOrder);

        selectedIndices = [];

        for idx = 1:numel(peakIndices)

            currentBin = ...
                peakIndices(idx);

            currentRange = ...
                rangeAxis(currentBin);

            if isempty(selectedIndices)

                isSeparated = true;

            else

                selectedRanges = ...
                    rangeAxis(selectedIndices);

                isSeparated = all( ...
                    abs( ...
                    selectedRanges ...
                    - currentRange) ...
                    >= cfg.minCandidateSeparation);
            end

            if isSeparated

                selectedIndices(end + 1) = ...
                    currentBin; %#ok<AGROW>

                if numel(selectedIndices) ...
                        >= cfg.maxCandidatesPerWindow
                    break;
                end
            end
        end

        for idx = 1:numel(selectedIndices)

            currentBin = ...
                selectedIndices(idx);

            currentVelocity = ...
                highSpeedVelocityMap( ...
                currentBin, ...
                windowIdx);

            if ~isfinite(currentVelocity)
                continue;
            end

            globalWindow(end + 1, 1) = ...
                windowIdx; %#ok<AGROW>

            physicalFrame(end + 1, 1) = ...
                targetData.windowPhysicalFrame( ...
                windowIdx); %#ok<AGROW>

            windowInFrame(end + 1, 1) = ...
                targetData.windowIndexInFrame( ...
                windowIdx); %#ok<AGROW>

            timeMs(end + 1, 1) = ...
                targetData.windowTimeMs( ...
                windowIdx); %#ok<AGROW>

            rangeM(end + 1, 1) = ...
                rangeAxis(currentBin); %#ok<AGROW>

            aliasedVelocity(end + 1, 1) = ...
                currentVelocity; %#ok<AGROW>

            relativeStrength(end + 1, 1) = ...
                profileSmooth(currentBin); %#ok<AGROW>

            rangeBin(end + 1, 1) = ...
                currentBin; %#ok<AGROW>
        end
    end

    candidateTable = table( ...
        globalWindow, ...
        physicalFrame, ...
        windowInFrame, ...
        timeMs, ...
        rangeM, ...
        aliasedVelocity, ...
        relativeStrength, ...
        rangeBin, ...
        'VariableNames', { ...
            'GlobalWindow', ...
            'PhysicalFrame', ...
            'WindowInFrame', ...
            'Time_ms', ...
            'Range_m', ...
            'AliasedVelocity_mps', ...
            'RelativeStrength_dB', ...
            'RangeBin'});
end

%% =========================================================
%  局部函数：使用鲁棒直线模型筛选连续轨迹
% ==========================================================

function [trackTable, fitInfo] = ...
        selectRobustTrack( ...
        candidateTable, ...
        cfg, ...
        derived)

    trackTable = table();

    fitInfo.valid = false;
    fitInfo.speed = NaN;
    fitInfo.intercept = NaN;
    fitInfo.rmse = NaN;

    if isempty(candidateTable)
        return;
    end

    validMask = ...
        candidateTable.Time_ms ...
        >= cfg.trackStartTimeMs;

    candidates = ...
        candidateTable(validMask, :);

    if height(candidates) < 2
        return;
    end

    numCandidates = ...
        height(candidates);

    bestSelection = [];
    bestCount = 0;
    bestMetric = -Inf;

    for firstIdx = 1:numCandidates - 1

        for secondIdx = ...
                firstIdx + 1:numCandidates

            if candidates.GlobalWindow(firstIdx) ...
                    == candidates.GlobalWindow(secondIdx)
                continue;
            end

            time1 = ...
                candidates.Time_ms(firstIdx) ...
                * 1e-3;

            time2 = ...
                candidates.Time_ms(secondIdx) ...
                * 1e-3;

            deltaTime = ...
                time2 - time1;

            if deltaTime <= 0
                continue;
            end

            range1 = ...
                candidates.Range_m(firstIdx);

            range2 = ...
                candidates.Range_m(secondIdx);

            speed = ...
                (range2 - range1) ...
                / deltaTime;

            if speed < cfg.fitSpeedMin ...
                    || speed > cfg.fitSpeedMax
                continue;
            end

            intercept = ...
                range1 ...
                - speed * time1;

            [selectedRows, residuals, aliasResiduals] = ...
                selectNearestPerWindow( ...
                candidates, ...
                speed, ...
                intercept, ...
                cfg.trackTolerance, ...
                cfg, ...
                derived);

            currentCount = ...
                numel(selectedRows);

            if currentCount == 0
                continue;
            end

            currentStrength = sum( ...
                max( ...
                candidates.RelativeStrength_dB( ...
                selectedRows), ...
                0));

            meanResidual = mean(residuals);

            meanAliasResidual = mean(aliasResiduals);

            metric = ...
                currentCount * 100 ...
                + currentStrength ...
                - meanResidual * 20 ...
                - 0.20 * meanAliasResidual;

            if currentCount > bestCount ...
                    || (currentCount == bestCount ...
                    && metric > bestMetric)

                bestCount = ...
                    currentCount;

                bestMetric = ...
                    metric;

                bestSelection = ...
                    selectedRows;
            end
        end
    end

    if bestCount < cfg.minTrackWindows
        return;
    end

    selectedRows = ...
        bestSelection;

    % 迭代重新拟合并重新选择每个窗口的最近候选
    for iteration = 1:4

        selectedTime = ...
            candidates.Time_ms( ...
            selectedRows) * 1e-3;

        selectedRange = ...
            candidates.Range_m( ...
            selectedRows);

        fitPolynomial = polyfit( ...
            selectedTime, ...
            selectedRange, ...
            1);

        speed = ...
            fitPolynomial(1);

        intercept = ...
            fitPolynomial(2);

        if speed < cfg.fitSpeedMin ...
                || speed > cfg.fitSpeedMax
            return;
        end

        [newSelection, ~, ~] = ...
            selectNearestPerWindow( ...
            candidates, ...
            speed, ...
            intercept, ...
            cfg.trackTolerance, ...
            cfg, ...
            derived);

        if isequal( ...
                sort(newSelection), ...
                sort(selectedRows))
            break;
        end

        selectedRows = ...
            newSelection;

        if numel(selectedRows) ...
                < cfg.minTrackWindows
            return;
        end
    end

    trackTable = ...
        candidates(selectedRows, :);

    trackTable = sortrows( ...
        trackTable, ...
        'Time_ms');

    fitPolynomial = polyfit( ...
        trackTable.Time_ms * 1e-3, ...
        trackTable.Range_m, ...
        1);

    fittedRange = polyval( ...
        fitPolynomial, ...
        trackTable.Time_ms * 1e-3);

    residual = ...
        trackTable.Range_m ...
        - fittedRange;

    trackTable.FittedRange_m = ...
        fittedRange;

    trackTable.FitResidual_m = ...
        residual;

    fitInfo.valid = true;
    fitInfo.speed = fitPolynomial(1);
    fitInfo.intercept = fitPolynomial(2);
    fitInfo.rmse = sqrt(mean(residual.^2));
end

%% =========================================================
%  局部函数：给定直线，每个窗口选择距离最近的候选
% ==========================================================

function [selectedRows, selectedResiduals, ...
        selectedAliasResiduals] = ...
        selectNearestPerWindow( ...
        candidates, ...
        speed, ...
        intercept, ...
        tolerance, ...
        cfg, ...
        derived)

    selectedRows = [];
    selectedResiduals = [];
    selectedAliasResiduals = [];

    uniqueWindows = unique( ...
        candidates.GlobalWindow, ...
        'stable');

    measuredAlias = ...
        wrapVelocity(cfg.measuredSpeed, derived.vMax);

    for idx = 1:numel(uniqueWindows)

        currentWindow = ...
            uniqueWindows(idx);

        rows = find( ...
            candidates.GlobalWindow ...
            == currentWindow);

        predictedRange = ...
            speed ...
            * candidates.Time_ms(rows) ...
            * 1e-3 ...
            + intercept;

        distanceResidual = abs( ...
            candidates.Range_m(rows) ...
            - predictedRange);

        validMask = ...
            distanceResidual <= tolerance;

        if ~any(validMask)
            continue;
        end

        validRows = rows(validMask);
        validDistanceResidual = ...
            distanceResidual(validMask);

        aliasResidual = ...
            circularVelocityDifference( ...
            candidates.AliasedVelocity_mps(validRows), ...
            measuredAlias, ...
            derived.velocityPeriod);

        strength = ...
            candidates.RelativeStrength_dB(validRows);

        combinedCost = ...
            (validDistanceResidual / tolerance).^2 ...
            + cfg.measuredAliasCostWeight ...
            * (aliasResidual ...
            / cfg.measuredAliasTolerance).^2 ...
            - cfg.trackStrengthCostWeight ...
            * max(strength, 0) ...
            / max(cfg.candidateThresholdDb, 1);

        [~, bestLocalIndex] = ...
            min(combinedCost);

        selectedRows(end + 1, 1) = ...
            validRows(bestLocalIndex); %#ok<AGROW>

        selectedResiduals(end + 1, 1) = ...
            validDistanceResidual(bestLocalIndex); %#ok<AGROW>

        selectedAliasResiduals(end + 1, 1) = ...
            aliasResidual(bestLocalIndex); %#ok<AGROW>
    end
end

function wrappedVelocity = ...
        wrapVelocity(velocity, vMax)

    period = 2 * vMax;

    wrappedVelocity = ...
        mod(velocity + vMax, period) ...
        - vMax;
end

function difference = ...
        circularVelocityDifference( ...
        velocity1, ...
        velocity2, ...
        period)

    directDifference = ...
        abs(velocity1 - velocity2);

    difference = min( ...
        directDifference, ...
        period - directDifference);
end

%% =========================================================
%  局部函数：基于实测速度先验的全局速度解模糊
% ==========================================================

function trackTable = unwrapTrackVelocity( ...
        trackTable, ...
        vMax, ...
        referenceSpeed, ...
        cfg)

    % =========================================================
    % 实测速度先验辅助的全局速度解模糊
    %
    % 对每个轨迹点构造：
    %   v(i,k) = v_alias(i) + k * 2Vmax
    %
    % 动态规划同时考虑：
    %   1. 与实测速度的偏差；
    %   2. 与距离拟合速度的偏差；
    %   3. 相邻点之间的速度连续性。
    % =========================================================

    ambiguityPeriod = ...
        2 * vMax;

    ambiguityCandidates = ...
        cfg.ambiguityNumberMin: ...
        cfg.ambiguityNumberMax;

    aliasedVelocity = ...
        double( ...
        trackTable.AliasedVelocity_mps(:));

    numPoints = ...
        numel(aliasedVelocity);

    numStates = ...
        numel(ambiguityCandidates);

    possibleVelocity = ...
        aliasedVelocity ...
        + ambiguityPeriod ...
        * ambiguityCandidates;

    validMask = ...
        possibleVelocity ...
        >= cfg.unwrapSpeedMin ...
        & possibleVelocity ...
        <= cfg.unwrapSpeedMax;

    measuredCost = ...
        cfg.unwrapMeasuredWeight ...
        * ((possibleVelocity ...
        - cfg.measuredSpeed) ...
        / cfg.measuredSpeedStd).^2;

    fitCost = ...
        cfg.unwrapFitWeight ...
        * ((possibleVelocity ...
        - referenceSpeed) ...
        / cfg.distanceFitSpeedStd).^2;

    localCost = ...
        measuredCost + fitCost;

    localCost(~validMask) = Inf;

    accumulatedCost = ...
        inf(numPoints, numStates);

    previousState = ...
        zeros(numPoints, numStates);

    accumulatedCost(1, :) = ...
        localCost(1, :);

    for pointIdx = 2:numPoints

        for stateIdx = 1:numStates

            if ~isfinite( ...
                    localCost(pointIdx, stateIdx))
                continue;
            end

            transitionCost = ...
                cfg.unwrapContinuityWeight ...
                * ((possibleVelocity( ...
                pointIdx, stateIdx) ...
                - possibleVelocity( ...
                pointIdx - 1, :)) ...
                / cfg.unwrapContinuityStd).^2;

            totalPreviousCost = ...
                accumulatedCost( ...
                pointIdx - 1, :) ...
                + transitionCost;

            [minimumPreviousCost, ...
                bestPreviousState] = min( ...
                totalPreviousCost);

            accumulatedCost( ...
                pointIdx, stateIdx) = ...
                localCost(pointIdx, stateIdx) ...
                + minimumPreviousCost;

            previousState( ...
                pointIdx, stateIdx) = ...
                bestPreviousState;
        end
    end

    [bestFinalCost, bestState] = ...
        min(accumulatedCost(end, :));

    if ~isfinite(bestFinalCost)

        warning( ...
            ['没有找到满足当前速度范围的' ...
             '有效解模糊路径。']);

        trackTable.AmbiguityNumber = ...
            nan(numPoints, 1);

        trackTable.UnwrappedVelocity_mps = ...
            nan(numPoints, 1);

        trackTable.MeasuredSpeed_mps = ...
            repmat( ...
            cfg.measuredSpeed, ...
            numPoints, 1);

        return;
    end

    bestStateSequence = ...
        zeros(numPoints, 1);

    bestStateSequence(end) = ...
        bestState;

    for pointIdx = numPoints:-1:2

        bestStateSequence( ...
            pointIdx - 1) = ...
            previousState( ...
            pointIdx, ...
            bestStateSequence(pointIdx));
    end

    linearIndex = sub2ind( ...
        size(possibleVelocity), ...
        (1:numPoints).', ...
        bestStateSequence);

    unwrappedVelocity = ...
        possibleVelocity(linearIndex);

    ambiguityNumber = ...
        ambiguityCandidates( ...
        bestStateSequence).';

    trackTable.AmbiguityNumber = ...
        ambiguityNumber;

    trackTable.UnwrappedVelocity_mps = ...
        unwrappedVelocity;

    trackTable.MeasuredSpeed_mps = ...
        repmat( ...
        cfg.measuredSpeed, ...
        numPoints, 1);

    trackTable.MeasuredSpeedResidual_mps = ...
        unwrappedVelocity ...
        - cfg.measuredSpeed;

    trackTable.DistanceFitSpeedResidual_mps = ...
        unwrappedVelocity ...
        - referenceSpeed;

    trackTable.GlobalUnwrapPathCost = ...
        repmat( ...
        bestFinalCost, ...
        numPoints, 1);
end

%% =========================================================
%  局部函数：分物理帧绘制二维图
% ==========================================================

function ax = drawSegmentedMap( ...
        timeAxisMs, ...
        rangeAxis, ...
        mapData, ...
        columnsPerFrame, ...
        numFrames, ...
        figureName, ...
        titleText, ...
        rangeLimits, ...
        colorLimits)

    fig = figure( ...
        'Name', figureName, ...
        'Color', 'w');

    ax = axes(fig);

    hold(ax, 'on');

    totalColumns = ...
        size(mapData, 2);

    for localFrameIdx = 1:numFrames

        firstColumn = ...
            (localFrameIdx - 1) ...
            * columnsPerFrame + 1;

        lastColumn = min( ...
            localFrameIdx ...
            * columnsPerFrame, ...
            totalColumns);

        if firstColumn > totalColumns
            break;
        end

        columns = ...
            firstColumn:lastColumn;

        imagesc( ...
            ax, ...
            timeAxisMs(columns), ...
            rangeAxis, ...
            mapData(:, columns));
    end

    hold(ax, 'off');

    ax.YDir = 'normal';
    ax.Box = 'on';

    xlabel(ax, 'Time (ms)');
    ylabel(ax, 'Range (m)');
    title(ax, titleText);

    ylim(ax, rangeLimits);

    finiteTime = ...
        timeAxisMs(isfinite(timeAxisMs));

    if ~isempty(finiteTime)

        timeMargin = 0.1;

        xlim(ax, ...
            [min(finiteTime) - timeMargin, ...
             max(finiteTime) + timeMargin]);
    end

    if ~isempty(colorLimits)
        caxis(ax, colorLimits);
    end

    colormap(ax, turbo);
    colorbar(ax);
end

%% =========================================================
%  局部函数：标记物理帧有效数据边界
% ==========================================================

function addFrameLines( ...
        ax, ...
        numFrames, ...
        framePeriod, ...
        activeDuration)

    hold(ax, 'on');

    for localFrameIdx = 1:numFrames

        frameStartMs = ...
            (localFrameIdx - 1) ...
            * framePeriod ...
            * 1e3;

        activeEndMs = ...
            frameStartMs ...
            + activeDuration ...
            * 1e3;

        xline( ...
            ax, ...
            activeEndMs, ...
            'w--', ...
            'LineWidth', 0.8);

        if localFrameIdx < numFrames

            nextFrameStartMs = ...
                localFrameIdx ...
                * framePeriod ...
                * 1e3;

            xline( ...
                ax, ...
                nextFrameStartMs, ...
                'w:', ...
                'LineWidth', 0.8);
        end
    end

    hold(ax, 'off');
end