clear;
clc;
close all;

%% Path

studyDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(studyDir);

addpath(fullfile(repoRoot, 'src'));
addpath(fullfile(repoRoot, 'configs'));

%% Configuration

cfg = config_0725_123207();
derived = pradar.deriveParameters(cfg);

dataFile = fullfile( ...
    repoRoot, 'data', '123207_frames_126_135.bin');

backgroundFrames = 1:8;

targetFrame = 9;
originalFrameNumber = 134;

%% Range-track parameters

timeRoiMs = [2.10, 3.05];
rangeRoi = [0.85, 1.85];

trackForwardGate_m = 0.20;
trackBackwardTolerance_m = 0.12;
trackSeedChirps = 8;
trackMedianLength = 5;

%% Time-frequency parameters

tfWindowLength = 32;
tfOverlap = tfWindowLength - 1;
tfNfft = 128;

stftClimDb = [-35, 0];
fsstClimDb = [-35, 0];

%% Ridge parameters

ridgeVelocityMin = 8;
ridgeVelocityMax = derived.vMax;

ridgeMaxStep_mps = 10;
ridgeContinuityPenalty = 0.20;

%% Basic parameters

lambda = derived.lambda;
Tc = cfg.chirpPeriod;
slowTimeFs = 1 / Tc;

fprintf('========================================\n');
fprintf('Single-frame time-frequency study\n');
fprintf('Original physical frame: %d\n', originalFrameNumber);
fprintf('Chirp period: %.3f us\n', Tc * 1e6);
fprintf('Slow-time sampling rate: %.3f kHz\n', ...
    slowTimeFs / 1e3);
fprintf('Maximum aliased velocity: +/- %.3f m/s\n', ...
    derived.vMax);
fprintf('TF window length: %d chirps\n', ...
    tfWindowLength);
fprintf('TF window duration: %.3f us\n', ...
    tfWindowLength * Tc * 1e6);
fprintf('========================================\n');

%% Open data

fid = fopen(dataFile, 'rb', 'ieee-le');

if fid < 0
    error('Unable to open data file: %s', dataFile);
end

cleanupObject = onCleanup(@() fclose(fid)); %#ok<NASGU>

%% Background range profile

numBackgroundChirps = ...
    numel(backgroundFrames) * cfg.numChirpsPerFrame;

backgroundRangePower = zeros( ...
    cfg.rangeFftSize, ...
    numBackgroundChirps, ...
    'single');

columnIndex = 1;

for frameIndex = backgroundFrames

    adcFrame = pradar.readDca1000Frame( ...
        fid, frameIndex, cfg, derived);

    rangeFft = fft( ...
        adcFrame .* derived.rangeWindow, ...
        cfg.rangeFftSize, 1);

    rangePower = sum(abs(rangeFft).^2, 3);

    columns = columnIndex: ...
        columnIndex + cfg.numChirpsPerFrame - 1;

    backgroundRangePower(:, columns) = ...
        single(rangePower);

    columnIndex = columns(end) + 1;
end

backgroundProfile = median( ...
    backgroundRangePower, 2, 'omitnan');

%% Target frame Range FFT

adcTarget = pradar.readDca1000Frame( ...
    fid, targetFrame, cfg, derived);

rangeFftTarget = fft( ...
    adcTarget .* derived.rangeWindow, ...
    cfg.rangeFftSize, 1);

rangePowerTarget = sum( ...
    abs(rangeFftTarget).^2, 3);

rangeEnhancedDb = 10 * log10( ...
    (double(rangePowerTarget) + 1e-12) ./ ...
    (double(backgroundProfile) + 1e-12));

chirpTimeMs = ...
    (0:cfg.numChirpsPerFrame-1) ...
    * Tc * 1e3;

%% Range-time ROI

timeMask = ...
    chirpTimeMs >= timeRoiMs(1) & ...
    chirpTimeMs <= timeRoiMs(2);

rangeMask = ...
    derived.rangeAxis >= rangeRoi(1) & ...
    derived.rangeAxis <= rangeRoi(2);

chirpIndices = find(timeMask);
rangeIndices = find(rangeMask);

%% Projectile range track

rawTrackRange = trackProjectileRange( ...
    rangeEnhancedDb, ...
    derived.rangeAxis, ...
    chirpIndices, ...
    rangeIndices, ...
    trackForwardGate_m, ...
    trackBackwardTolerance_m, ...
    trackSeedChirps);

filteredTrackRange = movmedian( ...
    rawTrackRange, ...
    trackMedianLength, ...
    'omitnan');

trackTimeSec = ...
    chirpTimeMs(chirpIndices) * 1e-3;

polyCoeff = polyfit( ...
    trackTimeSec, ...
    filteredTrackRange, ...
    2);

trackRange = polyval( ...
    polyCoeff, ...
    trackTimeSec);

trackRange = max( ...
    min(trackRange, rangeRoi(2)), ...
    rangeRoi(1));

%% Figure 1: range-time track

figure('Color', 'w');

imagesc( ...
    chirpTimeMs, ...
    derived.rangeAxis, ...
    rangeEnhancedDb);

axis xy;

xlim([0, cfg.numChirpsPerFrame * Tc * 1e3]);
ylim([0, 3]);

caxis([0, 15]);
colormap(turbo);
colorbar;

hold on;

hRaw = plot( ...
    chirpTimeMs(chirpIndices), ...
    rawTrackRange, ...
    'w.', ...
    'MarkerSize', 9);

hTrack = plot( ...
    chirpTimeMs(chirpIndices), ...
    trackRange, ...
    'r-', ...
    'LineWidth', 2);

hold off;

xlabel('Time (ms)');
ylabel('Range (m)');

title(sprintf( ...
    'Single-frame range-time tracking: physical frame %d', ...
    originalFrameNumber));

legend( ...
    [hRaw, hTrack], ...
    {'Raw range peak', 'Smoothed target track'}, ...
    'Location', 'best');

%% Extract complex signal along range track

numTrackChirps = numel(chirpIndices);

trackSignalRx = complex(zeros( ...
    numTrackChirps, ...
    cfg.numRx));

for timeIndex = 1:numTrackChirps

    chirpIndex = chirpIndices(timeIndex);
    targetRange = trackRange(timeIndex);

    for rxIndex = 1:cfg.numRx

        rangeData = double( ...
            rangeFftTarget(:, chirpIndex, rxIndex));

        trackSignalRx(timeIndex, rxIndex) = ...
            interp1( ...
            derived.rangeAxis, ...
            rangeData, ...
            targetRange, ...
            'linear', ...
            0);
    end
end

%% Multi-window time-frequency comparison

windowLengthList = [4, 8, 16, 32];
numCases = numel(windowLengthList);

stftResult = cell(numCases, 1);
fsstResult = cell(numCases, 1);

%% STFT comparison

figure('Color', 'w');

tiledlayout(2, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for caseIndex = 1:numCases

    windowLength = ...
        windowLengthList(caseIndex);

    overlapLength = ...
        windowLength - 1;

    tfWindow = ...
        pradar.makeHannWindow(windowLength);

    stftPower = [];

    for rxIndex = 1:cfg.numRx

        [stftRx, frequencyStft, timeStft] = ...
            spectrogram( ...
            trackSignalRx(:, rxIndex), ...
            tfWindow, ...
            overlapLength, ...
            tfNfft, ...
            slowTimeFs, ...
            'centered');

        if isempty(stftPower)
            stftPower = ...
                zeros(size(stftRx));
        end

        stftPower = ...
            stftPower ...
            + abs(stftRx).^2;
    end

    velocityStft = ...
        frequencyStft * lambda / 2;

    timeStftMs = ...
        chirpTimeMs(chirpIndices(1)) ...
        + timeStft * 1e3;

    stftPowerDb = ...
        10 * log10( ...
        stftPower ...
        / max(stftPower(:)) ...
        + 1e-12);

    ridgeVelocity = ...
        extractContinuousRidge( ...
        stftPower, ...
        velocityStft, ...
        [ridgeVelocityMin, ridgeVelocityMax], ...
        ridgeMaxStep_mps, ...
        ridgeContinuityPenalty);

    stftResult{caseIndex}.windowLength = ...
        windowLength;

    stftResult{caseIndex}.timeMs = ...
        timeStftMs;

    stftResult{caseIndex}.velocityAxis = ...
        velocityStft;

    stftResult{caseIndex}.powerDb = ...
        stftPowerDb;

    stftResult{caseIndex}.ridgeVelocity = ...
        ridgeVelocity;

    ax = nexttile;

    imagesc( ...
        ax, ...
        timeStftMs, ...
        velocityStft, ...
        stftPowerDb);

    axis(ax, 'xy');

    ylim(ax, ...
        [-derived.vMax, derived.vMax]);

    caxis(ax, [-35, 0]);

    hold(ax, 'on');

    plot( ...
        ax, ...
        timeStftMs, ...
        ridgeVelocity, ...
        'w-', ...
        'LineWidth', 1.6);

    hold(ax, 'off');

    xlabel(ax, 'Time (ms)');
    ylabel(ax, 'Aliased velocity (m/s)');

    title(ax, sprintf( ...
        '%d Chirps | %.0f \\mus', ...
        windowLength, ...
        windowLength * Tc * 1e6));

end

colormap(turbo);

sgtitle( ...
    sprintf( ...
    'STFT comparison using one physical frame %d', ...
    originalFrameNumber));

%% FSST comparison

if exist('fsst', 'file') == 2

    figure('Color', 'w');

    tiledlayout(2, 2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for caseIndex = 1:numCases

        windowLength = ...
            windowLengthList(caseIndex);

        tfWindow = ...
            pradar.makeHannWindow(windowLength);

        fsstPower = [];

        for rxIndex = 1:cfg.numRx

            [fsstRx, frequencyFsst, timeFsst] = ...
                fsst( ...
                trackSignalRx(:, rxIndex), ...
                slowTimeFs, ...
                tfWindow);

            if isempty(fsstPower)
                fsstPower = ...
                    zeros(size(fsstRx));
            end

            fsstPower = ...
                fsstPower ...
                + abs(fsstRx).^2;
        end

        velocityFsst = ...
            frequencyFsst * lambda / 2;

        timeFsstMs = ...
            chirpTimeMs(chirpIndices(1)) ...
            + timeFsst * 1e3;

        fsstPowerDb = ...
            10 * log10( ...
            fsstPower ...
            / max(fsstPower(:)) ...
            + 1e-12);

        ridgeVelocity = ...
            extractContinuousRidge( ...
            fsstPower, ...
            velocityFsst, ...
            [ridgeVelocityMin, ridgeVelocityMax], ...
            ridgeMaxStep_mps, ...
            ridgeContinuityPenalty);

        fsstResult{caseIndex}.windowLength = ...
            windowLength;

        fsstResult{caseIndex}.timeMs = ...
            timeFsstMs;

        fsstResult{caseIndex}.velocityAxis = ...
            velocityFsst;

        fsstResult{caseIndex}.powerDb = ...
            fsstPowerDb;

        fsstResult{caseIndex}.ridgeVelocity = ...
            ridgeVelocity;

        ax = nexttile;

        imagesc( ...
            ax, ...
            timeFsstMs, ...
            velocityFsst, ...
            fsstPowerDb);

        axis(ax, 'xy');

        ylim(ax, ...
            [-derived.vMax, derived.vMax]);

        caxis(ax, [-35, 0]);

        hold(ax, 'on');

        plot( ...
            ax, ...
            timeFsstMs, ...
            ridgeVelocity, ...
            'w-', ...
            'LineWidth', 1.6);

        hold(ax, 'off');

        xlabel(ax, 'Time (ms)');
        ylabel(ax, 'Aliased velocity (m/s)');

        title(ax, sprintf( ...
            '%d Chirps | %.0f \\mus', ...
            windowLength, ...
            windowLength * Tc * 1e6));

    end

    colormap(turbo);

    sgtitle( ...
        sprintf( ...
        'FSST comparison using one physical frame %d', ...
        originalFrameNumber));

end

%% Compare extracted STFT ridges

figure('Color', 'w');

hold on;

for caseIndex = 1:numCases

    plot( ...
        stftResult{caseIndex}.timeMs, ...
        stftResult{caseIndex}.ridgeVelocity, ...
        'LineWidth', 1.5, ...
        'DisplayName', ...
        sprintf('%d Chirps', ...
        windowLengthList(caseIndex)));

end

hold off;

grid on;
box on;

xlabel('Time (ms)');
ylabel('Aliased radial velocity (m/s)');

ylim([0, derived.vMax]);

title('STFT ridge comparison');

legend('Location', 'best');